# Generated by Django 5.2.9 on 2025-12-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_navoption_create_at_navoption_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navoption',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
