# Generated by Django 5.2.9 on 2025-12-27 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='title',
        ),
        migrations.AddField(
            model_name='button',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='button/'),
            preserve_default=False,
        ),
    ]
