# Generated by Django 5.2.9 on 2026-01-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_New_Arrival',
            field=models.BooleanField(default=True),
        ),
    ]
